export const COMMON_IS_AUTHENTICATED = 'COMMON_IS_AUTHENTICATED';

export const COMMON_LOGIN = 'COMMON_LOGIN';
export const COMMON_LOGOUT = 'COMMON_LOGOUT';

export const COMMON_GET_TOKEN_BEGIN = 'COMMON_GET_TOKEN_BEGIN';
export const COMMON_GET_TOKEN_SUCCESS = 'COMMON_GET_TOKEN_SUCCESS';
export const COMMON_GET_TOKEN_FAILURE = 'COMMON_GET_TOKEN_FAILURE';
export const COMMON_GET_TOKEN_DISMISS_ERROR = 'COMMON_GET_TOKEN_DISMISS_ERROR';
export const COMMON_AUTH = 'COMMON_AUTH';
